Moved location and flushed out mechanics of dialogue, along with other changes
amiwyn/Minestuck pull request #3
Opened 2021-07-27 03:46 UTC by Dweblenod

In addition to what is written in the commit message, I did some more reformatting(including of already existing files that hadnt been formatted) and changed a ColorHandler function name to be slightly less ambiguous

2021-07-27 03:49 UTC, Dweblenod commented
I may be one of the leading programmers active on the project so far but that does not mean I have anything except informal experience! Im sure there are some inappropriate usages of code that I am missing(like something not being static or private where it should be, etc)

2021-07-27 22:09 UTC, amiwyn requested changes
looking good! ill merge once you fix the conflicts

2021-07-27 22:09 UTC, amiwyn commented on src/main/java/com/mraof/minestuck/MinestuckConfig.java
> +			dialogueSpeed = builder.comment("Controls speed at which dialogue appears.")
nice addition!

2021-07-27 22:09 UTC, amiwyn commented on src/main/java/com/mraof/minestuck/client/gui/DialogueScreen.java
> +	private String[] dialogueText;
maybe add an 's' to make it clear its multiple "screens" of text shown

2021-07-27 22:09 UTC, amiwyn commented on src/main/java/com/mraof/minestuck/client/util/MSKeyHandler.java
> +				//Minecraft.getInstance().displayGuiScreen(new DialogueScreen(paragraphs, test, options, color));
you can remove that function entirely :D

2021-07-28 21:27 UTC, amiwyn commented
Hmm I fucked it up with git, I solved the conflicts but I lost your commit history. Im closing this, your changes are in my branch thanks!

2021-07-28 21:27 UTC, closed without merging

2021-07-29 00:25 UTC, Dweblenod commented
Sorry I hadnt gotten to make the changes in time, thank you for your work!